### PR TITLE
feat: enable metrics collection on docker compose example vec-409

### PR DESCRIPTION
**Pull request by dwelch-spike**

### CODE REVIEW

**Comment by dwelch-spike** [comment]
@hev I added metrics collection to the other compose files and centralized its config in the .internal directory. I tested these changes locally, each worked and metrics were visible on prometheus.

**Review by hev — APPROVED** [review]
I didnt test all the variations but approving.

**Review by hev — CHANGES_REQUESTED** [review]
I think we need to do some kind of disclosure here. Something like the following.

> This repo contains examples that collects basic usage data about the product including network information. You can opt out of this by disabling Prometheus in any of the install instructions.

**Comment by dwelch-spike** [comment]
> I think we need to do some kind of disclosure here. Something like the following.
> 
> > This repo contains examples that collects basic usage data about the product including network information. You can opt out of this by disabling Prometheus in any of the install instructions.

I added disclosures to the readme files

**Review by hev — APPROVED** [review]
Perfect. Looks good.

**Comment by dwelch-spike** [comment]
Tested locally after Joe reverted the service rename. docker, quote search, and prism search compose files all worked for me.

**Comment by dwelch-spike** [comment]
I'm going to do a little more testing tomorrow to make sure metrics are showing up in our monitoring stack still, then will merge this

**Review by hev — CHANGES_REQUESTED** [review]
Let's hold off on merging this. Waiting on feedback for leadership.

**Comment by hev** [comment]
No longer moving forward on this.

**Pull request closed without merging**
